cities/cities/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]

cities/mainapp/urls.py
from django.urls import path
from .views import HomePage, CityDetail


urlpatterns = [
    path('city/<slug:slug>/', CityDetail.as_view(), name='city'),
    path('', HomePage.as_view(), name='homepage'),
]

cities/mainapp/models.py
from django.db import models
from django.urls import reverse
from django.db.models import ForeignKey, CharField, SlugField
from django.db.models.deletion import SET_NULL


class City(models.Model):

    name = CharField(max_length=50, verbose_name='Название', unique=True)
    slug = SlugField(max_length=50, unique=True)

    def get_absolute_url(self) -> str:
        return reverse('city', kwargs={'slug': self.slug})

    def __str__(self) -> str:
        return self.name

    class Meta:

        verbose_name='город'
        verbose_name_plural='города'


class Citizen(models.Model):

    full_name = CharField(max_length=50, verbose_name='ФИО')
    city = ForeignKey(
        City,
        on_delete=SET_NULL,
        blank=True,
        null=True,
        verbose_name='город',
        related_name='citizens',
    )

    def get_absolute_url(self) -> str:
        return reverse('citizen', args=[self.pk])

    def __str__(self) -> str:
        return self.full_name

    class Meta:

        verbose_name='гражданин'
        verbose_name_plural='граждане'

cities/mainapp/views.py
from django.db.models import Count
from django.views.generic import ListView, DetailView
from .models import Citizen, City


class HomePage(ListView):

    template_name = 'mainapp/homepage.html'
    model = Citizen
    extra_context = {}

    def get_context_data(self, **kwargs):
        self.extra_context.update({
            'biggest_cities': City.objects.annotate(
                citizens_count=Count('citizens')
            ).order_by('-citizens_count')[:10]
        })
        return super().get_context_data(**kwargs)

class CityDetail(DetailView):

    model = City

cities/mainapp/templates/mainapp/city_detail.html
{% extends 'mainapp/index.html' %}
{% block main %}
  <h1>{{ city }}</h1>
  <table>
    <caption><h1>Граждане</h1></caption>
    <tr></tr>
    {% for citizen in city.citizens.all %}
    <tr>
      <td>{{ citizen }}</td>
    </tr>
    {% endfor %}
  </table>
{% endblock %}

cities/mainapp/templates/mainapp/header.html
{% block styles %}
<style>
    #navbar li{
        display: inline;
        font-size: xx-large;
    }
</style>
{% endblock %}

cities/mainapp/templates/mainapp/homepage.html
{% extends 'mainapp/index.html' %}
{% block main %}
  <table>
    <caption><h1>Граждане</h1></caption>
      <tr>
        <td><h3>ФИО</h3></td>
        <td><h3>Город</h3></td>
      </tr>
  {% for citizen in citizen_list %}
    <tr>
      <td>{{ citizen }}</td>
      <td><a href="{{ citizen.city.get_absolute_url }}"> {{ citizen.city }}</a></td>
    </tr>
  {% endfor %}
  </table>
  <table>
    <caption><h1>Самые населенные города</h1></caption>
    {% for city in biggest_cities %}
    <tr>
      <td><a href="{{ city.get_absolute_url }}">{{ city }}</a></td>
    </tr>
    {% endfor %}
  </table>
{% endblock %}

cities/mainapp/templates/mainapp/index.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    {% block styles %}
    {% endblock %}
  </head>
  <body>
    <header>
      {% include 'mainapp/header.html' %}
    </header>
    <main>
      {% block main %}
      {% endblock %}
    </main>
  </body>
</html>